exports.SUCCESS={
    status:'200',
    msg:'成功',
    result:''
}
exports.LOGIN_SUCCESS={
    status:'201',
    msg:'成功',
    result:'登录成功'
}
exports.LOGOUT_SUCCESS={
    status:'202',
    msg:'成功',
    result:'登出成功'
}
exports.ERROR={
    status:'400',
    msg:'失败',
    result:'未知错误'
}
exports.PASSWORD_ERROR={
    status:'1001',
    msg:'失败',
    result:'两次输入的密码不匹配'
}
exports.CAPTCHA_ERROR={
    status:'1002',
    msg:'失败',
    result:'验证码不正确'
}
exports.PHONE_EXIST={
    status:'1003',
    msg:'失败',
    result:'电话已被注册'
}
exports.EMAIL_EXIST={
    status:'1004',
    msg:'失败',
    result:'EMAIL已被注册'
}
exports.INSERT_ERROR={
    status:'1005',
    msg:'失败',
    result:'插入失败'
}
exports.PARAM_ERROR={
    status:'1006',
    msg:'失败',
    result:'参数异常'
}
exports.USER_NOT_EXIST={
    status:'1007',
    msg:'失败',
    result:'用户不存在'
}
exports.LOGIN_ERROR={
    status:'1008',
    msg:'失败',
    result:'登录失败，账户和密码不匹配'
}
exports.LOGOUT_ERROR={
    status:'1009',
    msg:'失败',
    result:'登出失败，用户尚未登录'
}
exports.PERMISSION_DENIED={
    status:'1010',
    msg:'失败',
    result:'没有权限，当前尚未登录'
}
exports.OLD_PASSWORD_ERROR={
    status:'1011',
    msg:'失败',
    result:'旧密码错误'
}